"""
HaulYeah — Full End-to-End System Test
Exercises every component: Config → Sheets → Outreach → Telegram → FB session check.
Safe: writes a clearly-labelled TEST lead to Sheets, then deletes it.

Usage (from trash_hauling_bot/ with venv active):
    python test_full_system.py
"""

import asyncio
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

# ── Must point at the real .env before importing config ──────────────────────
_REPO_ROOT = Path(__file__).parent.parent   # Claude-openclaw/
os.environ.setdefault("DOTENV_PATH_OVERRIDE", str(_REPO_ROOT / ".env"))

# Force live mode so we actually test real connections
os.environ["DRY_RUN"] = "false"

from dotenv import load_dotenv
load_dotenv(_REPO_ROOT / ".env", override=True)

# Now safe to import project modules
from config import config


# ─────────────────────────────────────────────────────────────────────────────
PASS = "✅ PASS"
FAIL = "❌ FAIL"
SKIP = "⚠️  SKIP"

results: dict[str, tuple[str, str]] = {}   # component → (status, detail)


def _section(title: str) -> None:
    print(f"\n{'─'*60}")
    print(f"  {title}")
    print(f"{'─'*60}")


# ─────────────────────────────────────────────────────────────────────────────
# 1. CONFIG
# ─────────────────────────────────────────────────────────────────────────────

def test_config() -> None:
    _section("1 · Config & Environment")
    missing = config.validate()
    if missing:
        results["config"] = (FAIL, f"Missing: {', '.join(missing)}")
        print(f"  {FAIL}  Missing keys: {missing}")
        return

    checks = {
        "bot_token":    bool(config.bot_token),
        "sheet_id":     bool(config.google_sheet_id),
        "fb_location":  bool(config.fb_search_location),
        "creds_file":   Path(config.google_credentials_file).exists(),
        "dry_run=false": not config.dry_run,
        "keywords":     len(config.fb_search_keywords) > 0,
        "chat_ids":     len(config.authorized_chat_ids) > 0,
        "team_ids":     len(config.team_chat_ids) > 0,
    }
    failed = [k for k, v in checks.items() if not v]

    if failed:
        results["config"] = (FAIL, f"Failed checks: {', '.join(failed)}")
        print(f"  {FAIL}  {', '.join(failed)}")
    else:
        results["config"] = (PASS, "All required config present")
        print(f"  {PASS}  All config present")

    print(f"  dry_run   : {config.dry_run}")
    print(f"  location  : {config.fb_search_location}")
    print(f"  keywords  : {config.fb_search_keywords}")
    print(f"  sheet_id  : {'set' if config.google_sheet_id else 'MISSING'}")
    print(f"  chat_ids  : {len(config.authorized_chat_ids)} authorized, {len(config.team_chat_ids)} team")


# ─────────────────────────────────────────────────────────────────────────────
# 2. GOOGLE SHEETS
# ─────────────────────────────────────────────────────────────────────────────

def test_sheets() -> str | None:
    """Returns the lead_id of the test lead if written, so we can clean up."""
    _section("2 · Google Sheets (live read + write + delete)")
    from integrations.sheets import SheetsClient, COLUMNS

    test_lead_id = None
    try:
        sc = SheetsClient()
        print("  Connected to Google Sheets ✓")

        # Write a clearly-labelled test lead
        test_payload = {
            "name":           "TEST_LEAD — auto-generated by test_full_system.py",
            "contact":        "test@haulyeah.test",
            "listing_url":    "https://www.facebook.com/marketplace/item/TEST000000/",
            "job_type":       "TEST junk removal",
            "description":    "System test entry — safe to delete. Generated by test_full_system.py.",
            "location":       config.fb_search_location,
            "urgency_score":  1,
            "size_score":     1,
        }
        test_lead_id = sc.add_lead(test_payload)
        print(f"  Lead written  → id={test_lead_id}")

        # Read it back
        lead = sc.get_lead_by_id(test_lead_id)
        if not lead:
            results["sheets"] = (FAIL, "Lead written but not readable")
            print(f"  {FAIL}  Lead not found after write")
            return test_lead_id

        print(f"  Lead read back → status={lead.get('status')} ✓")

        # Sanity check: status should be "new"
        if lead.get("status") != "new":
            results["sheets"] = (FAIL, f"Unexpected status: {lead.get('status')}")
            return test_lead_id

        # Count existing leads
        new_count = len(sc.get_leads_by_status("new"))
        print(f"  Total 'new' leads in sheet: {new_count}")

        results["sheets"] = (PASS, f"Write + read confirmed (id={test_lead_id})")
        print(f"  {PASS}  Sheets read/write working")
        return test_lead_id

    except Exception as exc:
        results["sheets"] = (FAIL, str(exc))
        print(f"  {FAIL}  {exc}")
        return test_lead_id


def cleanup_test_lead(lead_id: str | None) -> None:
    """Mark the test lead 'declined' so it's clearly swept up later."""
    if not lead_id:
        return
    try:
        from integrations.sheets import SheetsClient
        sc = SheetsClient()
        sc.update_lead(lead_id, {"status": "declined", "response_notes": "AUTO-DELETED by test_full_system.py"})
        print(f"\n  [cleanup] Test lead {lead_id} marked declined ✓")
    except Exception as exc:
        print(f"\n  [cleanup] Could not clean up {lead_id}: {exc}")


# ─────────────────────────────────────────────────────────────────────────────
# 3. OUTREACH MESSAGE GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def test_outreach() -> None:
    _section("3 · Outreach Message Generation")
    try:
        from utils.audit import AuditLogger
        from agents.outreach import OutreachAgent

        audit = AuditLogger(config.audit_log_file)
        agent = OutreachAgent(audit)

        sample_lead = {
            "id":          "test_outreach_lead",
            "job_type":    "junk removal",
            "description": "Moving out, need someone to haul away old furniture and appliances.",
            "location":    "Dallas, TX",
        }
        msg = agent._generate_message(sample_lead)

        if not msg or len(msg) < 20:
            results["outreach"] = (FAIL, "Generated message too short or empty")
            print(f"  {FAIL}  Empty/short message")
            return

        claude_used = "claude" not in msg.lower() or config.anthropic_api_key != ""
        mode = "Claude API" if config.anthropic_api_key else "template fallback"
        results["outreach"] = (PASS, f"Message generated via {mode}")
        print(f"  {PASS}  Message ({len(msg)} chars) via {mode}")
        print(f"  Preview: {msg[:120]}...")

    except Exception as exc:
        results["outreach"] = (FAIL, str(exc))
        print(f"  {FAIL}  {exc}")


# ─────────────────────────────────────────────────────────────────────────────
# 4. TELEGRAM BOT PING
# ─────────────────────────────────────────────────────────────────────────────

async def test_telegram() -> None:
    _section("4 · Telegram Bot Ping")
    if not config.bot_token:
        results["telegram"] = (FAIL, "TRASH_BOT_TOKEN not set")
        print(f"  {FAIL}  No bot token")
        return
    if not config.team_chat_ids:
        results["telegram"] = (SKIP, "TRASH_BOT_TEAM_CHAT_IDS empty — no chat to ping")
        print(f"  {SKIP}  TRASH_BOT_TEAM_CHAT_IDS is empty; set it to enable notifications")
        return

    try:
        from telegram import Bot
        bot = Bot(token=config.bot_token)
        me = await bot.get_me()
        print(f"  Bot identity : @{me.username} (id={me.id}) ✓")

        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        msg = (
            f"🟢 *HaulYeah System Test — {ts}*\n"
            f"All components under test. This is an automated ping from `test_full_system.py`.\n"
            f"If you see this, Telegram notifications are working."
        )
        for chat_id in config.team_chat_ids:
            sent = await bot.send_message(chat_id=chat_id, text=msg, parse_mode="Markdown")
            print(f"  Message sent  → chat_id={chat_id} msg_id={sent.message_id} ✓")

        results["telegram"] = (PASS, f"Pinged {len(config.team_chat_ids)} chat(s)")
        print(f"  {PASS}  Telegram working")

    except Exception as exc:
        results["telegram"] = (FAIL, str(exc))
        print(f"  {FAIL}  {exc}")


# ─────────────────────────────────────────────────────────────────────────────
# 5. FACEBOOK SESSION CHECK
# ─────────────────────────────────────────────────────────────────────────────

async def test_fb_session() -> None:
    _section("5 · Facebook Marketplace Session")
    profile_dir = Path(config.fb_profile_dir)

    if not profile_dir.exists() or not any(profile_dir.iterdir()):
        results["fb_session"] = (SKIP, "No FB profile dir — run: python -m agents.scraper --login")
        print(f"  {SKIP}  FB profile not found at {profile_dir}")
        print("         Run: python -m agents.scraper --login")
        return

    print(f"  FB profile exists: {profile_dir} ✓")

    # Quick Playwright check: does FB redirect to login?
    try:
        from playwright.async_api import async_playwright
        from agents.scraper import _USER_AGENT

        async with async_playwright() as pw:
            ctx = await pw.chromium.launch_persistent_context(
                str(profile_dir),
                headless=True,
                channel="chrome",
                args=["--no-sandbox", "--disable-blink-features=AutomationControlled"],
                user_agent=_USER_AGENT,
            )
            page = await ctx.new_page()
            await page.set_extra_http_headers({"Accept-Language": "en-US,en;q=0.9"})

            test_url = (
                "https://www.facebook.com/marketplace/search/"
                "?query=junk+removal&sortBy=creation_time_descend"
            )
            print(f"  Loading FB Marketplace (headless)…")
            await page.goto(test_url, timeout=30_000, wait_until="domcontentloaded")

            import asyncio as _asyncio
            await _asyncio.sleep(2.5)

            final_url = page.url
            has_login_form = await page.query_selector('input[name="email"]')

            if "login" in final_url.lower() or has_login_form:
                results["fb_session"] = (FAIL, "FB login wall — session expired. Run --login")
                print(f"  {FAIL}  FB redirected to login. Session cookie expired.")
                print("         Fix: python -m agents.scraper --login")
            else:
                # Count listings visible
                links = await page.query_selector_all('a[href*="/marketplace/item/"]')
                results["fb_session"] = (PASS, f"Logged in, found {len(links)} listing links")
                print(f"  {PASS}  FB session valid — {len(links)} listing link(s) visible")

            await ctx.close()

    except Exception as exc:
        results["fb_session"] = (FAIL, str(exc))
        print(f"  {FAIL}  Playwright error: {exc}")


# ─────────────────────────────────────────────────────────────────────────────
# 6. SUMMARY
# ─────────────────────────────────────────────────────────────────────────────

def print_summary() -> None:
    _section("SUMMARY")
    order = ["config", "sheets", "outreach", "telegram", "fb_session"]
    all_pass = True
    for key in order:
        status, detail = results.get(key, (SKIP, "not run"))
        print(f"  {status}  {key:<12}  {detail}")
        if status == FAIL:
            all_pass = False

    print()
    if all_pass:
        print("  🎉  All tests passed — HaulYeah is fully operational!")
    else:
        print("  ⚠️   Some tests failed — see above for details.")

    # Write results file
    out = Path(config.data_dir) / "test_full_system_results.txt"
    out.parent.mkdir(exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"HaulYeah Full System Test — {datetime.now()}\n\n")
        for key in order:
            status, detail = results.get(key, (SKIP, "not run"))
            f.write(f"{status}  {key}: {detail}\n")
    print(f"\n  Results saved → {out}")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

async def run_all() -> None:
    print(f"\n{'='*60}")
    print(f"  HaulYeah — Full System Test")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'='*60}")

    test_config()

    # Stop here if config is broken — nothing else will work
    if results.get("config", (FAIL,))[0] == FAIL:
        print("\n  Config failed — skipping remaining tests.")
        print_summary()
        return

    test_lead_id = test_sheets()
    test_outreach()
    await test_telegram()
    await test_fb_session()

    cleanup_test_lead(test_lead_id)
    print_summary()


if __name__ == "__main__":
    asyncio.run(run_all())
